apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
    - secrets
    providers:
    #- identity: {} #If you want to decript all the secrets, uncommnet this line and comment the last line
    - aescbc:
        keys:
        - name: key1
          secret: fkr010ULyeP5lXDQqQr8DzOpDQJxq5jAZLQ0ka9u29k= #<BASE 64 ENCODED SECRET>
    - identity: {}